import Navbar from '@/components/Navbar'
import '@/styles/global.css'
import { Raleway } from 'next/font/google'

const mukta = Raleway({
  subsets: ['latin'],
weight: ['300' ,'400' ,'500','600', '700' ,'800' ,'900' ,], })

export const metadata = {
  title: "Suffa Mehfil'23",
  description: 'Generated by create next app',
}

export default function RootLayout({children}){
  return(
    <html lang='en'>
      <body className={mukta.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
